crud_project_1/crud_project_1/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views
from django.conf.urls import url
from crud_application_1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('std', views.std),
    path('', views.show),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
]

crud_project_1/models.py
from django.db import models
import json

# Create your models here.

# Create your models here.
class Student(models.Model):
    sid = models.IntegerField()
    sname = models.CharField(max_length=100)
    sage = models.IntegerField()
    sdepartment = models.CharField(max_length=100)
    ssubject = models.TextField(default='[]')

    @property
    def list(self):
        return json.loads(self._list)

    @list.setter
    def list(self, value):
        self._list = json.dumps(self.list + value)

    class Meta:
        db_table = "student"

crud_project_1/crud_application_1/forms.py
from django import forms
from crud_application_1.models import Student

class Student_form(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

crud_project_1/crud_application_1/views.py
from django.shortcuts import render,redirect
from crud_application_1.forms import Student_form
from crud_application_1.models import Student

# Create your views here.

def welcome_page(request):
    return render(request, 'welcome.html')

def std(request):
    if request.method == "POST":
        form = Student_form(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = Student_form()
    return render(request, "index.html", {'form':form})

def show(request):
    students = Student.objects.all()
    return render(request, "show.html", {'students':students})

def edit(request, id):
    students = Student.objects.get(id=id)
    return render(request, "edit.html", {'student':students})

def update(request, id):
    students = Student.objects.get(id=id)
    form = Student_form(request.POST, instance=students)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, "edit.html", {'students':students})

def delete(request, id):
    students = Student.objects.get(id=id)
    students.delete()
    return redirect("/show")

crud_project_1/crud_application_1/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> edit page </title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
  </head>
  <body>
    <form class="post-form" action="/update/{{student.id}}" method="post">
      {% csrf_token %}
      <div class="container">
        <br>

        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">student id:</label>
          <div class="col-sm-4">
            <input type="text" name="sid" value="{{ student.sid }}" id="id_sid" required maxlength="10"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">student name:</label>
          <div class="col-sm-4">
            <input type="text" name="sname" value="{{ student.sname }}" id="id_sname" required maxlength="100"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">student age:</label>
          <div class="col-sm-4">
            <input type="text" name="sage" value="{{ student.sage }}" id="id_sage" required maxlength="20"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">student department:</label>
          <div class="col-sm-4">
            <input type="text" name="sdepartment" value="{{ student.sdepartment }}" id="id_sdepartment" required maxlength="100"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">student subjects:</label>
          <div class="col-sm-4">
            <input type="text" name="ssubject" value="{{ student.ssubject }}" id="id_ssubject" required maxlength="200"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>

      </div>
    </form>

  </body>
</html>

crud_project_1/crud_application_1/templates/index.html
<!<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title> index </title>
  {% load static %}
  <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
  <form method="POST" class="post-from" action="/std">
    {%  csrf_token %}
    <div class="container">
      <br>
      <div class="from-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3> enter details</h3>
        </div>
      </div>
        <div class="form-group row">
        <lebel class="col-sm-2 cal-from-label"> student id:</label>
        <div class="coll-sm-4">
          {{ form.sid }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> student name:</label>
      <div class="col-sm-4">
          {{ form.sname }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> student age:</label>
      <div class="col-sm-4">
          {{ form.sage }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> student department:</label>
      <div class="col-sm-4">
          {{ form.sdepartment }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"> student subject:</label>
      <div class="col-sm-4">
          {{ form.ssubject }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
      </br>
    </div>
</body>

</html>

crud_project_1/crud_application_1/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title> student records </title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}">
  </head>
  <body>
    <table class="table table-striped table-bordered table-sm">
      <thead class="thead-dark">
        <tr>
          <th>student id</th>
          <th>student name</th>
          <th>student age</th>
          <th>student department</th>
          <th>student subjects</th>
          <th>----------------------</th>
          <th>action</th>
        </tr>
      </thead>
      <tbody>
  {% for item in students %}
  <tr>
    <td>{{ item.sid }}</td>
    <td>{{ item.sname }}</td>
    <td>{{ item.sage }}</td>
    <td>{{ item.sdepartment }}</td>
    <td>{{ item.ssubject }}</td>
    <td></td>

    <td>
      <a href="/edit/{{ item.id }}"><span class="glyphicon flyphicon-pencil"> edit </span></a>
      <a href="/delete/{{ item.id }}">Delete</a>
    </td>
  </tr>
  {% endfor %}
      </tbody>
  </table>
  <br>
  <br>
  <center><a href="/std" class="btn btn-primary">Add New Record</a></center>

  </body>
</html>

crud_project_1/crud_application_1/templates/welcome.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    <header>
  		<div class="main">
  			<ul>
          <li><a href="{% url 'welcome' %}">Home</a></li>
  				<li><a href="{% url 'show' %}">show</a></li>
  				<li><a href="{% url 'update' %}">update</a></li>
  				<li><a href="{% url 'delete' %}">delete</a></li>

  			</ul>
  		</div>
  	</header>
  </body>